version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  rails:
    build: .
    volumes:
      - ./rails_app:/var/www/rails_app
      - gem_cache:/usr/local/bundle
      - node_modules:/var/www/rails_app/node_modules
    ports:
      - "3000:3000"
    # environment:
      # PG_PASSWORD: password
      # RAILS_ENV: development
    #env_file: .env
    depends_on:
      - db
volumes:
  gem_cache:
  db_data:
  node_modules:
